on:
  rss:
    url: https://rss.evangelizo.org/rss/v2/evangelizo_rss-de.xml
    config:
      format: |
        item.contentSnippet = item.title.substring(item.title.search(' : ') + 3).replace(/ /g, '%20').replace(/,/g, '%2C').replace(/\./g, '%2E').replace(/-/g, '%2D')
        return item;
jobs:
  print:
    name: Print
    runs-on: ubuntu-latest
    steps:
      - name: Print Outputs
        env:
          title: ${{on.rss.outputs.title}}
          contentSnippet: ${{on.rss.outputs.contentSnippet}}
          link: ${{on.rss.outputs.link}}
        run: |
          echo title: $title
          echo contentSnippet: $contentSnippet
          echo link: $link
